# Generated by Django 4.0.6 on 2022-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('MA', 'پسر'), ('FE', 'دختر')], max_length=2)),
                ('status', models.CharField(choices=[('RE', 'درخواست تحویل'), ('SE', 'فرستاده شده'), ('DE', 'تحویل داده شده')], max_length=2)),
            ],
        ),
    ]
