# Generated by Django 4.0.6 on 2022-08-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='parent',
            field=models.CharField(choices=[('MO', 'مادر'), ('FA', 'پدر')], default='FA', max_length=2),
            preserve_default=False,
        ),
    ]
