# Generated by Django 4.0.6 on 2022-08-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_kid_options_alter_kid_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['-number', 'name']},
        ),
    ]
