# Generated by Django 4.0.6 on 2022-08-04 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_kid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['status', 'gender', 'gate_in', 'gate_out', 'first_name', 'last_name', '-number']},
        ),
        migrations.RemoveField(
            model_name='kid',
            name='name',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='user',
        ),
        migrations.AddField(
            model_name='kid',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(1396, 1, 1)),
        ),
        migrations.AddField(
            model_name='kid',
            name='caretaker',
            field=models.CharField(blank=True, default='ندارد', max_length=100),
        ),
        migrations.AddField(
            model_name='kid',
            name='caretaker_name',
            field=models.CharField(blank=True, default='ندارد', max_length=100),
        ),
        migrations.AddField(
            model_name='kid',
            name='caretaker_phone_number',
            field=models.CharField(blank=True, default='000000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='kid',
            name='emergancy_calls',
            field=models.CharField(blank=True, default='ندارد', max_length=255),
        ),
        migrations.AddField(
            model_name='kid',
            name='first_name',
            field=models.CharField(blank=True, default='ندارد', max_length=100),
        ),
        migrations.AddField(
            model_name='kid',
            name='gate_in',
            field=models.CharField(blank=True, choices=[('MA', 'آقایان'), ('FE', 'خانمها'), ('NO', 'معلوم نیست')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='kid',
            name='gate_out',
            field=models.CharField(blank=True, choices=[('MA', 'آقایان'), ('FE', 'خانمها'), ('NO', 'معلوم نیست')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='kid',
            name='last_name',
            field=models.CharField(blank=True, default='ندارد', max_length=100),
        ),
        migrations.AlterField(
            model_name='kid',
            name='gender',
            field=models.CharField(blank=True, choices=[('MA', 'پسر'), ('FE', 'دختر'), ('NO', 'معلوم نیست')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='kid',
            name='number',
            field=models.CharField(blank=True, default='000', max_length=5),
        ),
        migrations.AlterField(
            model_name='kid',
            name='status',
            field=models.CharField(blank=True, choices=[('NO', 'نیامده'), ('IN', 'داخل غرفه'), ('RE', 'درخواست تحویل'), ('SE', 'فرستاده شده'), ('DE', 'تحویل داده شده')], default='NO', max_length=2),
        ),
    ]
