# Generated by Django 4.0.6 on 2022-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_kid_options_remove_kid_name_remove_kid_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='caretaker_home_number',
            field=models.CharField(blank=True, default='ندارد', max_length=15),
        ),
        migrations.AddField(
            model_name='kid',
            name='wc',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='kid',
            name='caretaker_phone_number',
            field=models.CharField(blank=True, default='ندارد', max_length=15),
        ),
    ]
