# Generated by Django 4.0.6 on 2022-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_kid_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['-status', 'gender', 'gate_in', 'gate_out', 'first_name', 'last_name', '-number']},
        ),
        migrations.AlterField(
            model_name='kid',
            name='status',
            field=models.CharField(blank=True, choices=[('RE', 'درخواست تحویل'), ('DE', 'تحویل داده شده'), ('SE', 'فرستاده شده'), ('IN', 'داخل غرفه'), ('NO', 'نیامده')], default='NO', max_length=2),
        ),
    ]
