# Generated by Django 4.0.6 on 2022-08-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_kid_options_alter_kid_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['status', 'gender', 'gate_in', 'gate_out', 'first_name', 'last_name', '-number']},
        ),
    ]
