# Generated by Django 4.0.6 on 2022-08-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_kid_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='last_change',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
