# Generated by Django 4.0.6 on 2022-08-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_kid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['-last_change', 'status', 'gender', 'gate_in', 'gate_out', 'first_name', 'last_name', '-number']},
        ),
    ]
