# Generated by Django 4.0.6 on 2022-08-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_kid_porsline_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['last_change', 'status', 'gender', 'gate_in', 'gate_out', 'first_name', 'last_name', '-number']},
        ),
    ]
