# Generated by Django 4.0.6 on 2024-07-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_statuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
